language: node_js
node_js:
- '8'
before_install:
- npm i -g @angular/cli@1.6.3
script:
- ng build --prod
before_deploy:
- cd dist
deploy:
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_AUTH_TOKEN"
  skip_cleanup: true
  on:
    tags: true
notifications:
  slack:
    secure: i8305/Rnte67v7/p5C4EDPJuV7wm+ZrkONCXfUuX66urftNNV+Qch3m0NFxFTNIyAH64tHukHVb5+qxAXw7rjr29QGBw7+XQoOcaY9g0iFEzJ6gyA6rdRmyrGyiMpIfBsxZK4PNCTDIPApKHIP+ZxPq4E9wsSm35nNz+eID+WqlGv90bImcv504FecGeDmQMIfphIL9X/N9Q3t1dGAXbtrWLazowd266B0kDP6H34gSWqDDejlaWL6JQiHHG1MDlBFXlTMJaplmLlf311rzOzVESYE23MRm41OuByjL7ETG3kgMa+u6wsBRyjXxOTwzVb29HhKS6f0x6Dmrd1YQNIUE2giH9baERIsXWL2mP97sQifN1FBvsFvl6g8+xYduvkJVHhu8GYkiIy+8yg2DFKMZp0CxZvu8tSlqqK/beQoYBfr1uHI1deJo3JyBQtUEe+buP9/Iu0D8zOxmysnXHeDt089I7ijPpgwaMFrcXXiclkQShIRuzsOFTGM9o+241r33ZCH6zySVSnMYF9c9mdu6dFmFLiWCHE3QhqTsVOQ2bXSvmqRxGA0Ce8W/VTx0MVyrqIQQErUx4KpLmqLI3qTLBrhTccc/Lgdbpz6bc//44Us4vEFn7whgCr6iQtn/WoqL3bvsxTANIlHqKTodLykWpH/QHjAudV6hAgDstrZ4=
